name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          set -e
          echo "Attempting npm ci"
          if npm ci; then
            echo "npm ci succeeded"
          else
            echo "npm ci failed; retrying with --legacy-peer-deps"
            if npm ci --legacy-peer-deps; then
              echo "npm ci with legacy peer deps succeeded"
            else
              echo "npm ci still failing due to lock mismatch; falling back to npm install to update lockfile for this run"
              npm install
            fi
          fi

      - name: Build Angular (Project Page)
        # Adjust base-href below if you deploy to a user/org root or a custom domain
        run: npm run build -- --base-href "/Hospital-catering/"

      - name: Add SPA fallback (404.html)
        run: cp dist/catering-frontend/index.html dist/catering-frontend/404.html

      - name: Show build output (diagnostic)
        run: |
          node -v
          npm -v
          ls -la
          echo "--- dist contents ---"
          ls -la dist || true
          echo "--- catering-frontend contents ---"
          ls -la dist/catering-frontend || true

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist/catering-frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
